spring:
  datasource:
    db-master:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3308/db1?serverTimezone=UTC&useSSL=true
      username: root
      password: root
    db-read:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3307/db1?serverTimezone=UTC&useSSL=true
      username: admin
      password: admin
  aop:
    auto: true


